---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: github-pat
  url: https://github.com/marcoippel/gitops-secrets

