apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  releaseName: prometheus-adapter
  chart:
    spec:
      chart: prometheus-adapter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  values:
    prometheus:
      url: http://prometheus.monitoring.svc
      port: 80
    rules:
      default: false
      external:
      - seriesQuery: 'jobs_in_queue_total'
        # resources:
        #   overrides:
        #     kubernetes_namespace: {resource: "namespace"}
        #     kubernetes_pod_name: {resource: "pod"}
        name:
          matches: "jobs_in_queue_total"
          as: "jobs_in_queue_total"
        metricsQuery: 'ceil(sum(avg_over_time(<<.Series>>[2m])))'