apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  values:
    alertmanager:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    pushgateway:
      enabled: false
    extraScrapeConfigs: |
      - job_name: 'buildqueuemonitoring'
        metrics_path: /metrics
        static_configs:
          - targets: ['buildqueuemonitoring.monitoring.svc:80']
            labels:
              kubernetes_namespace: 'monitoring'