apiVersion: v1
data:
  config.yaml: |
    externalRules:
    - seriesQuery: 'jobs_in_queue_total{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name:
        matches: "jobs_in_queue_total"
        as: "jobs_in_queue_total"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
kind: ConfigMap
metadata:
  labels:
    app: prometheus-adapter
  name: prometheus-adapter
