prometheus:
  url: http://prometheus-server.default.svc
  port: 80
rules:
  external:
  - seriesQuery: '{__name__=~"^my_queue_len$"}'
    resources:
      #template: <<.Resource>>
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}
    name:
      matches: ""
      as: "my_queue"
    metricsQuery: sum(my_queue_len)