apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - svc_prometheus.yaml
  - svc_cadvisor.yaml
  - deployment.yaml
  - ingress.yaml
  - rbac.yaml
configMapGenerator:
  - name: prometheus
    files:
      - prometheus.yml
