apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildqueuemonitoring
  labels:
    app: buildqueuemonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildqueuemonitoring
  template:
    metadata:
      labels:
        app: buildqueuemonitoring
    spec:
      containers:
      - image: marcoippel/buildqueuemonitoring:1.0.0-7d2d93c
        name: metrics-provider
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ADO_PAT
          valueFrom:
            secretKeyRef:
              name: azuredevops-pat
              key: AZP_TOKEN
        - name: ADO_ORGANIZATION
          value: marcoippel
        - name: ADO_POOLNAME
          value: kubernetes-demo
        - name: ADO_URL
          value: https://dev.azure.com