apiVersion: v1
kind: Service
metadata:
  labels:
    app: BuildQueueMonitoring
  name: BuildQueueMonitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: BuildQueueMonitoring
  type: ClusterIP