kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: buildqueuemonitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buildqueuemonitoring

  # autoscale between 1 and 10 replicas
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      metricName: jobs_in_queue_total
      targetAverageValue: 30m