apiVersion: v1
kind: Service
metadata:
  labels:
    app: buildqueuemonitoring
  name: buildqueuemonitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: buildqueuemonitoring
  type: ClusterIP