apiVersion: v1
data:
  config.yaml: |
    rules:
    - seriesQuery: 'jobs_in_queue_total{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name:
        matches: "jobs_in_queue_total"
        as: "jobs_in_queue_total"
      metricsQuery: 'sum(rate(<<.Series>>{kubernetes_namespace="monitoring",kubernetes_pod_name=~"buildqueuemonitoring-.+"}[2m])) by (<<.GroupBy>>)'
kind: ConfigMap
metadata:
  labels:
    app: prometheus-adapter
  name: prometheus-adapter

# sum(rate(jobs_in_queue_total{kubernetes_namespace="monitoring",kubernetes_pod_name="buildqueuemonitoring-d7bb6596b-6dqs6"}[2m]))