apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azdevops-agent
  metrics:
  - type: Object
    object:
      metricName: jobs_in_queue_total
      target:
        apiVersion: v1
        kind: Pod
        name: buildqueuemonitoring # This is my rabbitmq service name
      targetValue: 20