apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-agent
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
        public-access: allow
    spec:
      containers:
      - name: azuredevops-buildagent
        image: marcoippel/buildagent:1.0.0-53d8afa
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/Marcoippel/"
          - name: AZP_POOL
            value: "kubernetes-demo"
          - name: AZP_AGENT_NAME
            value: "k8s-agent"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azuredevops-pat
                key: AZP_TOKEN