apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
  annotations:
    # to make sure that the deployment is always redeployed it is an alternative for --recreate-pods
    rollme: {{ randAlphaNum 10 | quote }}
spec:
  replicas: 1 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
        public-access: allow
    spec:
      containers:
      - name: azuredevops-buildagent
        image: topaasts.azurecr.io/azuredevops-buildagent:latest
        env:
          - name: AZP_URL
            value: {{ .Values.env.AZP_URL | quote}}
          - name: AZP_POOL
            value: {{ .Values.env.AZP_POOL | quote}}
          - name: AZP_AGENT_NAME
            value: {{ .Values.env.AZP_AGENT_NAME | quote}}
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azuredevops-pat
                key: AZP_TOKEN