kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: buildqueuemonitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azdevops-agent

  # autoscale between 1 and 10 replicas
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: External
    external:
      metricName: jobs_in_queue_total
      targetValue: "5"