name: BuildAgent

on:
  push:
    branches: [ main ]
    paths:
      - "src/BuildAgent/**"
      - ".github/actions/**"
      - ".github/workflows/BuildAgent.yml" 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      project: BuildAgent
      projectLower: buildagent
    defaults:
      run:
        working-directory: ./src/BuildAgent

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build and push image
        uses: marcoippel/k8s-autoscaling/.github/actions/build-docker-image@main
        with:
          docker-username: ${{ secrets.dockerhub_username }}
          docker-password: ${{ secrets.dockerhub_password }}
          docker-image-repo: 'marcoippel/${{env.projectLower}}'
          working-directory: './src/${{env.project}}'
          docker-image-version: '1.0.0'