name: BuildQueueMonitoring

on:
  push:
    branches: [ main ]
    paths:
      - "src/GoBuildQueueMonitor/**"
      - ".github/actions/**"
      - ".github/workflows/BuildQueueMonitoring.yml" 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      project: BuildQueueMonitoring
      projectLower: buildqueuemonitoring
    defaults:
      run:
        working-directory: ./src/GoBuildQueueMonitor

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build and push image
        uses: marcoippel/k8s-autoscaling/.github/actions/build-docker-image@main
        with:
          docker-username: ${{ secrets.dockerhub_username }}
          docker-password: ${{ secrets.dockerhub_password }}
          docker-image-repo: 'marcoippel/${{env.projectLower}}'
          working-directory: './src/${{env.project}}'
          docker-image-version: '1.0.0'